#!/bin/sh

APP_MUSTACHE_JSON_FILE_NAME="app.mustache.json"
APP_MUSTACHE_FILE_NAME="app.mustache"
APP_VIEW_FILE_NAME="app.html"

BASEDIR=$(dirname $0)
PROJECT_ROOT="$(cat ${BASEDIR}/${APP_MUSTACHE_JSON_FILE_NAME} | underscore select '.root')"
PROJECT_ROOT="$(echo $PROJECT_ROOT | sed -e "s/\[\"//g" | sed -e "s/\"\]//g")"

APP_MUSTACHE_JSON_PATH="${BASEDIR}/${APP_MUSTACHE_JSON_FILE_NAME}"
APP_MUSTACHE_PATH="${PROJECT_ROOT}/${APP_MUSTACHE_FILE_NAME}"
APP_VIEW_PATH="${BASEDIR}/${APP_VIEW_FILE_NAME}"

cd "${BASEDIR}/"
mustache $APP_MUSTACHE_JSON_PATH $APP_MUSTACHE_PATH > $APP_VIEW_PATH